# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ERC:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: setsoft/kicad_auto:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Vemos que hay
      run: ls /usr/bin

    # Runs a set of commands using the runners shell
    - name: Vemos si esta el workspace
      run: |
        echo $GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE
