name: Simple KiBot CI/CD test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# If any of the listed file changes we run the workflow
on:
  push:
    branches: [ master ]
    paths:
      - 'kicad_ci_test.kicad_sch'
      - 'kicad_ci_test.kicad_pcb'
      - 'kicad_ci_test.kibot.yaml'
      - '.github/workflows/test1.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'kicad_ci_test.kicad_sch'
      - 'kicad_ci_test.kicad_pcb'
      - 'kicad_ci_test.kibot.yaml'
      - '.github/workflows/test1.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    # Here use kicad_auto_test:latest to get all features, i.e. Blender render
    # Or even use ghcr.io/inti-cmnb/kicad8_auto_full:dev to get the last fixes
    # In this case change "8" by the KiCad you need. Also don't forget to change this tag
    # once your project is finished, pointing to a stable KiBot release
    # Use the same for all steps
    container: ghcr.io/inti-cmnb/kicad8_auto:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      run: |
        [ -f *.kicad_sch ] && kibot  -d Fabrication -s update_xml,run_drc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Fabrication

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      run: |
        [ -f *.kicad_pcb ] && kibot  -d Fabrication -s update_xml,erc -i

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: Fabrication

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run schematic stuff
      run: |
        [ -f *.kicad_sch ] && kibot  -d Fabrication -s drc,erc print_sch

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: FabSch_Output
        path: Fabrication

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v4

    - name: Run PCB stuff
      run: |
        [ -f *.kicad_pcb ] && kibot  -d Fabrication -s all print_front gerbers

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: FabPCB_Output
        path: Fabrication


