name: Sub-dir and sub-project KiBot CI/CD example

# Controls when the action will run. Triggers the workflow on push or pull request
# events
# If any of the listed file changes we run the workflow
on:
  push:
    # Use the following syntax to limit on which branches we run the workflow
    # branches: [ master ]
    paths:
      - 'test_subdir/test_subdir.kicad_sch'
      - 'test_subdir/test_subdir.kicad_pcb'
      - 'test_subdir/test_subdir.kibot.yaml'
      - 'test_subdir/Makefile'
      - '.github/workflows/test_subdir.yml'
  pull_request:
    # branches: [ master ]
    paths:
      - 'test_subdir/test_subdir.kicad_sch'
      - 'test_subdir/test_subdir.kicad_pcb'
      - 'test_subdir/test_subdir.kibot.yaml'
      - 'test_subdir/Makefile'
      - '.github/workflows/test_subdir.yml'
  schedule:
    # Run on Wednesday @ 5:43 to keep the artifacts alive
    - cron: '43 5 * * 3'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run ERC
      run: |
        ls -la test_subdir/
        make -C test_subdir/ erc

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: test_subdir/Fabrication

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run DRC
      run: |
        make -C test_subdir/ drc

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: test_subdir/Fabrication

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run schematic stuff
      run: |
        make -C test_subdir/ sch_fab

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: FabSch_Output
        path: test_subdir/Fabrication

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Run PCB stuff
      run: |
        make -C test_subdir/ pcb_fab

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: FabPCB_Output
        path: test_subdir/Fabrication
